# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170303_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=100),
        ),
    ]
