# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_file_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.FileField(upload_to='res/')),
                ('name', models.CharField(default='', max_length=100)),
                ('describtion', models.CharField(default='', max_length=200)),
                ('prof', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='username',
        ),
        migrations.DeleteModel(
            name='file',
        ),
    ]
